[ENH] make single problem loaders for equal length problems return numpy arrays
scikit-time/scikit-time pull request #109
Opened 2023-02-25 10:50 UTC by TonyBagnall

change the return_type from None to numpy3d and remove the very long comments describing possible data structures in unnecessary detail.

2023-02-25 11:00 UTC, patrickzib requested changes
Two suggestions:
- Change default in load_UCR_UEA_dataset to numpy3d
- Remove support for numpy2d

2023-02-25 11:00 UTC, patrickzib commented on sktime/datasets/_single_problem_loaders.py
> +    >>> X, y = load_UCR_UEA_dataset(name="ArrowHead", return_type="numpy3d")
Wouldn't it be better to change the API call instead of the example call? Currently the api call still defaults to None.

```python
def load_UCR_UEA_dataset(
    name, split=None, return_X_y=True, return_type="numpy3d", extract_path=None
):
```

2023-02-25 11:00 UTC, patrickzib commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
Can we remove `numpy2d`? It will not work with transformers for classification

2023-02-25 11:00 UTC, patrickzib commented on sktime/datasets/_single_problem_loaders.py
>      return _load_dataset(name, split, return_X_y, return_type, extract_path)
General comment: remove numpy2d for loading datasets?

2023-02-25 11:08 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +    >>> X, y = load_UCR_UEA_dataset(name="ArrowHead", return_type="numpy3d")
need to resolve the unequal length issue before doing that, was going to just get this in first and wait, this is mostly cosmetic

2023-02-25 11:10 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
sure, although it works with all classifiers and is closest to scikit. Maybe I'll just give some examples with reshape

2023-02-25 11:12 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +    >>> X, y = load_UCR_UEA_dataset(name="ArrowHead", return_type="numpy3d")
> 

yes using this PR to find all calls in the notebooks :)

2023-02-25 11:13 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +    >>> X, y = load_UCR_UEA_dataset(name="ArrowHead", return_type="numpy3d")
but dont want to do too much, next job is to rewrite the classification notebook anyway

2023-02-25 11:19 UTC, patrickzib commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
True. I would love to have numpy2d support, as it it closest so scikit-learn. But then we should got for the transformer instead to support numpy2d input correctly..

2023-02-25 11:32 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
in time we shall! But this is a very incremental change, just removing the essays on weird supported types and shifting more to numpy

2023-02-25 11:34 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
actually I think I would prefer to leave the text allowing numpy2d in there, and lets just raise an issue about the transformers, listing all those effected. Is that ok?

2023-02-25 11:40 UTC, TonyBagnall commented on sktime/datasets/_single_problem_loaders.py
> +        Data structure to use for time series, should be either "numpy2d" or "numpy3d".
because if I actually stop the return_type argument and always return 3D numpy, there are a million old legacy calls that will break in places like the "benchmarking" module

2023-02-25 11:42 UTC, TonyBagnall commented
> Two suggestions:
> 
> * Change default in load_UCR_UEA_dataset to numpy3d
> * Remove support for numpy2d



> Two suggestions:
> 
> * Change default in load_UCR_UEA_dataset to numpy3d

its in the cards, I think I will change the name to load_tsc_problem, but it needs to also load unequal problems so was going to delay until we remove DataFrames all together

> * Remove support for numpy2d

see my other comments

2023-02-26 07:10 UTC, TonyBagnall commented
I had no idea that the single problem loaders were used so much in testing (other than correctness testing), this is surely not a good idea, will raise an issue

2023-02-27 10:42 UTC, TonyBagnall commented
well, that tweak to kill time on a saturday morning became a monster!

2023-02-27 11:06 UTC, patrickzib commented
I would give you a badge of honour! :)

2023-02-27 13:37 UTC, MatthewMiddlehurst commented on examples/minirocket.ipynb
> +    "X_train, y_train = load_basic_motions(split=\"train\")"
Seemed to have missed this and line 330 when replacing the return type, unless the swap to numpy was intentional.

2023-02-27 13:37 UTC, MatthewMiddlehurst commented on sktime/benchmarking/tests/test_orchestration.py
> -    data = data_loader(return_X_y=False)
Seems like you can add the new return type here instead of removing the test? No idea what the test is doing or if it will stay in the long run.

2023-02-27 13:37 UTC, MatthewMiddlehurst commented on sktime/datasets/_data_io.py
> -        Exception is raised if the data cannot be stored in the requested type.
Think these can be simplified, but not to the current extent. loading into pandas is still available functionality.

2023-02-27 14:14 UTC, TonyBagnall commented on examples/minirocket.ipynb
> +    "X_train, y_train = load_basic_motions(split=\"train\")"
want to use numpy where I can, had to switch one above because it used pandas plot, but will tidy up these in a subsequent PR

2023-02-27 14:15 UTC, TonyBagnall commented on sktime/benchmarking/tests/test_orchestration.py
> -    data = data_loader(return_X_y=False)
well I would like shot of it #116 but I guess you are correct, will put it back

2023-02-27 14:15 UTC, TonyBagnall commented on sktime/datasets/_data_io.py
> -        Exception is raised if the data cannot be stored in the requested type.
yes, maybe over zealous there, will rework it

2023-02-28 13:23 UTC, patrickzib reviewed
Some default types in `_data_io.py` do not seem to match. Might be worth checking? Found some at least.

2023-02-28 13:23 UTC, patrickzib commented on examples/02_classification.ipynb
> +    "2. Dimension ensembling via `ColumnEnsembleClassifier` in which one classifier is fitted for each time series column/dimension of the time series and their predictions are combined through a vot
Channel? ;)

2023-02-28 13:23 UTC, patrickzib commented on examples/AA_datatypes_and_datasets.ipynb
> +    "* instances: rows with the same \"instance index\" index value correspond to the same instance; rows with different \"instance index\" values correspond to different instances.\n",
"Index index" ? value

2023-02-28 13:23 UTC, patrickzib commented on sktime/datasets/_data_io.py
> +    return_data_type : str, optional, default = "nested_univ"
default is wrong.should be `none`

2023-02-28 13:23 UTC, patrickzib commented on sktime/datasets/_data_io.py
>      return_X_y: bool, optional (default=True)
```suggestion
    return_X_y: bool, optional (default=True)
```

There is no default? (it is not true)

2023-02-28 13:23 UTC, patrickzib commented on sktime/datasets/_data_io.py
> +    extract_path : path of the location for the data file.
default=None

2023-02-28 15:32 UTC, TonyBagnall commented on examples/02_classification.ipynb
> +    "2. Dimension ensembling via `ColumnEnsembleClassifier` in which one classifier is fitted for each time series column/dimension of the time series and their predictions are combined through a vot
I'm completely reworking this note book in this https://github.com/scikit-time/scikit-time/pull/123 so I'll leave that until then

2023-02-28 15:33 UTC, TonyBagnall commented on examples/AA_datatypes_and_datasets.ipynb
> +    "* instances: rows with the same \"instance index\" index value correspond to the same instance; rows with different \"instance index\" values correspond to different instances.\n",
dont get me started on this notebook .... job for a different PR

2023-02-28 15:39 UTC, TonyBagnall commented on sktime/datasets/_data_io.py
>      return_X_y: bool, optional (default=True)
good spot, fixed

2023-02-28 15:39 UTC, TonyBagnall commented on sktime/datasets/_data_io.py
> +    extract_path : path of the location for the data file.
fixed

2023-02-28 15:40 UTC, TonyBagnall commented
thanks for the review @patrickzib , think I have addressed all issues now

2023-02-28 18:50 UTC, patrickzib approved these changes
well done. thank you.

2023-02-28 19:09 UTC, merged