Update README (IN PROGRESS)
scikit-time/scikit-time pull request #63
Opened 2023-02-14 17:21 UTC by MatthewMiddlehurst

The current README is a disclaimer and needs to be replaced.

2023-02-16 23:29 UTC, GuzalBulatova requested changes
Thank you very much, @MatthewMiddlehurst , great work! I think this is ready as soon as the faulty links are replaced.

2023-02-16 23:29 UTC, GuzalBulatova commented on README.md
> +<a href="https://scikit-time.org"><img src="https://github.com/scikit-time/scikit-time/blob/main/docs/source/images/scikit-time-logo.jpg?raw=true)" width="175" align="right" /></a>
<img width="1113" alt="Screenshot 2023-02-16 at 23 18 50" src="https://user-images.githubusercontent.com/73598322/219509910-a2ff5df0-91f0-4d80-b641-742777e7a48c.png">
Doesn't render for me, is it just on my end?

2023-02-16 23:29 UTC, GuzalBulatova commented on README.md
> +| **Community** | [![!slack](https://img.shields.io/static/v1?logo=slack&label=slack&message=chat&color=lightgreen)](https://join.slack.com/t/scikit-time-group/shared_invite/zt-1cghagwee-sqLJ~eHWGYgz
Slack throws a "there's been a glitch" error now if I click the link
LinkedIn page "isn't available", Twitter too

2023-02-16 23:29 UTC, GuzalBulatova commented on README.md
> +[tutorials]: https://www.scikit-time.org/en/latest/tutorials.html
Is it a placeholder there for the logo on scikit-time website? 
<img width="1113" alt="Screenshot 2023-02-16 at 23 22 56" src="https://user-images.githubusercontent.com/73598322/219510444-5e0141c5-0542-459c-899f-c7c6a782223f.png">

2023-02-16 23:29 UTC, GuzalBulatova commented on README.md
> +[slack]: https://join.slack.com/t/scikit-time-group/shared_invite/zt-1cghagwee-sqLJ~eHWGYgzWbqUX937ig
This link is faulty on my end as well

2023-02-16 23:29 UTC, GuzalBulatova commented on README.md
> +| :globe_with_meridians: **Community collaboration session** | ?                      |
Maybe put Slack here for now?

2023-02-18 15:08 UTC, TonyBagnall reviewed
I suggest putting a link to the new slack in the disclaimer and directing people there (in addition to the permanent slack link)

2023-02-20 15:14 UTC, MatthewMiddlehurst commented on README.md
> +[tutorials]: https://www.scikit-time.org/en/latest/tutorials.html
yes replaced all the sktime logos in a previous commit

2023-02-20 15:15 UTC, MatthewMiddlehurst commented on README.md
> +| :globe_with_meridians: **Community collaboration session** | ?                      |
Think we can just remove it for now, can add it again when we are ready to host such sessions

2023-02-20 16:09 UTC, aiwalter approved these changes
Probably not the final state of README but an improvement - so approving

2023-02-20 17:13 UTC, patrickzib approved these changes
Thank you!

2023-02-20 22:39 UTC, GuzalBulatova approved these changes
Looks ready now, thank you @MatthewMiddlehurst

2023-02-21 09:09 UTC, merged